version: '2'
services:
  crc:
    image: app-docker136.hex.tno.nl:443/pitch/crc:5.3.2.1L
    environment:
      DISPLAY: xserver
  xserver:
    image: app-docker136.hex.tno.nl:443/library/xserver
    ports:
    - 443:8080/tcp